# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "portmanagement.xcodeproj")
    
    # Configurar para App Store (no TestFlight)
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "portmanagement.xcodeproj",
      team_id: "Y86MT47MC7"
    )
    
    # Configurar build para App Store
    build_app(
      workspace: "portmanagement.xcworkspace", 
      scheme: "PortManagement",
      configuration: "Release",
      export_method: "app-store",
      include_bitcode: true,
      include_symbols: true,
      xcargs: "-allowProvisioningUpdates"
    )
    upload_to_app_store(
      skip_binary_upload: false,
      submit_for_review: false,
      username: "albertosolpal@gmail.com"
    )
    clean_build_artifacts
  end

  desc "Push a new release build to Testflight"
  lane :beta do
    increment_build_number(xcodeproj: "portmanagement.xcodeproj")
    # Use automatic signing temporarily to avoid provisioning profile issues
    update_code_signing_settings(
      use_automatic_signing: true,
      path: "portmanagement.xcodeproj",
      team_id: "Y86MT47MC7"
    )
    build_app(
      workspace: "portmanagement.xcworkspace", 
      scheme: "PortManagement",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      username: "albertosolpal@gmail.com"
    )
    clean_build_artifacts
  end

end
